In [1]:
import numpy as np

In [5]:
a= np.array([1,2,3])
a

array([1, 2, 3])

### Random Array Generate

In [6]:
np.random.random(3)

array([0.10719992, 0.46077169, 0.61007365])

### Arithmetic Operation

Addition (+)

In [7]:
a = np.array([1,2,3])
a + 4

array([5, 6, 7])

Two Matrices Addition 

In [10]:
a = np.array([1,2,3])
b = np.array([4,3,2])
a + b

array([5, 5, 5])

### Python List Vs Numpy

In [12]:
py_list =  [1,2,3]
print("Python List Multiplication: ", py_list*2)

np_list = np.array([1,2,3])
print("Python List Multiplication: ", np_list*2)


Python List Multiplication:  [1, 2, 3, 1, 2, 3]
Python List Multiplication:  [2 4 6]


### Creating Array from Scratch

In [18]:
zeros = np.zeros((2,2))
print("zeroes array are : \n", zeros)

ones = np.ones((2,2))
print("zeroes array are : \n", ones)

zeroes array are : 
 [[0. 0.]
 [0. 0.]]
zeroes array are : 
 [[1. 1.]
 [1. 1.]]


In [19]:
### Vector, Matrix and Tensor

In [21]:
vector = np.array([1,2,3])
print('Vector are: ', vector)

matrix = np.array([[1,2,3],[4,5,6]])
print('Matrix are: \n', matrix)

tensor = np.array([[[1,2,3],[4,5,6]]])
print('Tensor are: \n', tensor)


Vector are:  [1 2 3]
Matrix are: 
 [[1 2 3]
 [4 5 6]]
Tensor are: 
 [[[1 2 3]
  [4 5 6]]]


### Array Properties

In [22]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size)
print("Data Type ", arr.dtype)

Shape  (2, 3)
Dimension  2
Size  6
Data Type  int32
