In [2]:
import numpy as np # type: ignore

### Array Splitting

In [5]:
A = np.arange(16).reshape((4,4))
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [9]:
# Horizontal Array 
[B,C] = np.hsplit(A,2)
print("Horizontal Array \n" ,B) 
print("Without Horizontal Array \n" ,C) 

Horizontal Array 
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Without Horizontal Array 
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [ ]:
# Vertical Array
